-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 09:37:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HospitalManage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HospitalManage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HospitalManage` ;
USE `HospitalManage` ;

-- -----------------------------------------------------
-- Table `HospitalManage`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalManage`.`Patient` (
  `idPatient` INT NOT NULL,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `DOB` DATETIME NULL,
  `appointmentID` INT NULL,
  `Gender` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone Number` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalManage`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalManage`.`Staff` (
  `idStaff` INT NOT NULL,
  `fName`  NULL,
  `lname` VARCHAR(45) NULL,
  `Salary` INT NULL,
  `JobTitle` VARCHAR(45) NULL,
  `DOB` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `idDepartment` VARCHAR(45) NULL,
  PRIMARY KEY (`idStaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalManage`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalManage`.`Department` (
  `idDepartment` INT NOT NULL,
  `DepartmentName` VARCHAR(45) NULL,
  `DepartmentFloor` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalManage`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalManage`.`Doctor` (
  `idStaff` INT NOT NULL,
  `idAppointments` INT NULL,
  `OfficeNum` VARCHAR(45) NULL,
  `idDepartment` INT NULL,
  `Department_idDepartment` INT NOT NULL,
  UNIQUE INDEX `idStaff_UNIQUE` (`idStaff` ASC) VISIBLE,
  PRIMARY KEY (`idStaff`, `Department_idDepartment`),
  INDEX `fk_Doctor_Department1_idx` (`Department_idDepartment` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `HospitalManage`.`Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Department1`
    FOREIGN KEY (`Department_idDepartment`)
    REFERENCES `HospitalManage`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalManage`.`Nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalManage`.`Nurse` (
  `idStaff` INT NOT NULL,
  `Schedule` VARCHAR(45) NULL,
  UNIQUE INDEX `idStaff_UNIQUE` (`idStaff` ASC) VISIBLE,
  PRIMARY KEY (`idStaff`),
  CONSTRAINT `fk_Nurse_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `HospitalManage`.`Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalManage`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalManage`.`Appointments` (
  `idAppointments` INT NOT NULL,
  `idPatient` INT NULL,
  `idDoctor` INT NULL,
  `AppointmentDate` DATETIME NULL,
  `Completed` BLOB NULL,
  `AppointmentTime` DATETIME NULL,
  `Doctor_idStaff` INT NOT NULL,
  `Patient_idPatient` INT NOT NULL,
  PRIMARY KEY (`idAppointments`),
  INDEX `fk_Appointments_Doctor1_idx` (`Doctor_idStaff` ASC) VISIBLE,
  INDEX `fk_Appointments_Patient1_idx` (`Patient_idPatient` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_Doctor1`
    FOREIGN KEY (`Doctor_idStaff`)
    REFERENCES `HospitalManage`.`Doctor` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointments_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `HospitalManage`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalManage`.`Patient_has_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalManage`.`Patient_has_Doctor` (
  `Patient_idPatient` INT NOT NULL,
  `Doctor_idStaff` INT NOT NULL,
  PRIMARY KEY (`Patient_idPatient`, `Doctor_idStaff`),
  INDEX `fk_Patient_has_Doctor_Doctor1_idx` (`Doctor_idStaff` ASC) VISIBLE,
  INDEX `fk_Patient_has_Doctor_Patient1_idx` (`Patient_idPatient` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_has_Doctor_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `HospitalManage`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_has_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_idStaff`)
    REFERENCES `HospitalManage`.`Doctor` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'Nurse';

GRANT SELECT, INSERT, TRIGGER ON TABLE `HospitalManage`.* TO 'Nurse';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `HospitalManage`.* TO 'Nurse';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
