-- MySQL Script generated by MySQL Workbench
-- Fri Apr 14 12:12:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Staff` (
  `idStaff` INT NOT NULL,
  `fName`  NULL,
  `lname` VARCHAR(45) NULL,
  `Salary` INT NULL,
  `JobTitle` VARCHAR(45) NULL,
  `DOB` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`idStaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Doctor` (
  `idDoctor` INT NOT NULL,
  `idStaff` INT NULL,
  `idDepartment` INT NOT NULL,
  PRIMARY KEY (`idDoctor`),
  UNIQUE INDEX `idDoctor_UNIQUE` (`idDoctor` ASC) VISIBLE,
  UNIQUE INDEX `idStaff_UNIQUE` (`idStaff` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `new_schema1`.`Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Appointments` (
  `idAppointments` INT NOT NULL,
  `idPatient` INT NULL,
  `idDoctor` INT NULL,
  `AppointmentDate` DATETIME NULL,
  `Completed` BLOB NULL,
  `AppointmentTime` DATETIME NULL,
  `Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idAppointments`),
  INDEX `fk_Appointments_Doctor1_idx` (`Doctor_idDoctor` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `new_schema1`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Patient` (
  `idPatient` INT NOT NULL,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `DOB` DATETIME NULL,
  `appointmentID` INT NULL,
  `Gender` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Phone Number` VARCHAR(45) NULL,
  `Appointments_idAppointments` INT NOT NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `fk_Patient_Appointments1_idx` (`Appointments_idAppointments` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Appointments1`
    FOREIGN KEY (`Appointments_idAppointments`)
    REFERENCES `new_schema1`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Department` (
  `idDepartment` INT NOT NULL,
  `DepartmentName` VARCHAR(45) NULL,
  `DepartmentFloor` VARCHAR(45) NULL,
  `Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idDepartment`),
  INDEX `fk_Department_Doctor1_idx` (`Doctor_idDoctor` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `new_schema1`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Nurse` (
  `idNurse` INT NOT NULL,
  `idStaff` INT NULL,
  `idDepartment` INT NULL,
  PRIMARY KEY (`idNurse`),
  UNIQUE INDEX `idNurse_UNIQUE` (`idNurse` ASC) VISIBLE,
  UNIQUE INDEX `idStaff_UNIQUE` (`idStaff` ASC) VISIBLE,
  UNIQUE INDEX `idDepartment_UNIQUE` (`idDepartment` ASC) VISIBLE,
  CONSTRAINT `fk_Nurse_Department1`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `new_schema1`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurse_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `new_schema1`.`Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'Nurse';

GRANT SELECT, INSERT, TRIGGER ON TABLE `new_schema1`.* TO 'Nurse';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `new_schema1`.* TO 'Nurse';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
